# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: ThermosCook_development
  pool: 5
test:
  adapter: postgresql
  database: ThermosCook_test
  pool: 5
